# conda
name: sbs-helper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.2
  - pip
  - pip:
    - pip-tools
    - ipynb
    - yfinance==0.2.27
    - plotly==5.15.0  
    - beautifulsoup4==4.12.3
    - tabula-py==2.7.0
    - seleniumbase==4.34.3
    - playwright
    - pyautogui==0.9.54
  - pyyaml
  - pyarrow  
  - pandas=1.5.3
  - numpy==1.24.4
  - ipykernel
  - nbformat==5.8.0
  - openpyxl==3.0.7
  - pyxlsb==1.0.9
  - twine==3.8.0
  - boto3==1.34.0
  - xlrd==2.0.1